#!/usr/bin/env python3
"""Generate clock-period SDC variants for sweep runs."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from pipeline_common import (
    dump_json,
    generated_sdc_path,
    load_json,
    planned_runs_from_config,
    repo_root,
    resolve_path,
)

CLK_RE = re.compile(r"^(\s*set\s+clk_period\s+)([^\s]+)(.*)$")


def rewrite_clk_period(template_text: str, clock_period_ns: float) -> str:
    replaced = False
    out_lines = []
    for line in template_text.splitlines():
        m = CLK_RE.match(line)
        if m and not replaced:
            out_lines.append(f"{m.group(1)}{clock_period_ns:.3f}{m.group(3)}")
            replaced = True
        else:
            out_lines.append(line)
    if not replaced:
        raise ValueError("Could not find 'set clk_period' line in SDC template")
    return "\n".join(out_lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SDC files for all configured runs")
    parser.add_argument("--config", default="configs/sweep_phase1.json", help="Path to sweep config JSON")
    parser.add_argument("--overwrite", action="store_true", help="Overwrite existing generated SDC files")
    args = parser.parse_args()

    root = repo_root()
    config_path = resolve_path(args.config, root)
    config = load_json(config_path)
    runs = planned_runs_from_config(config)

    template_map = config.get("template_sdc")
    if not isinstance(template_map, dict):
        raise ValueError("Config must define 'template_sdc' mapping")

    written = 0
    skipped = 0
    seen = set()
    for run in runs:
        design = run["design"]
        period = run["clock_period_ns"]
        key = (design, period)
        if key in seen:
            continue
        seen.add(key)

        if design not in template_map:
            raise ValueError(f"No template SDC configured for design '{design}'")

        template_path = resolve_path(str(template_map[design]), root)
        template_text = template_path.read_text(encoding="utf-8")

        out_path = generated_sdc_path(config, design, period, root)
        out_path.parent.mkdir(parents=True, exist_ok=True)

        if out_path.exists() and not args.overwrite:
            skipped += 1
            continue

        body = rewrite_clk_period(template_text, period)
        header = (
            "# AUTO-GENERATED by scripts/gen_sdc_variants.py\n"
            f"# Template: {template_path}\n"
            f"# Clock period (ns): {period:.3f}\n"
        )
        out_path.write_text(header + body, encoding="utf-8")
        written += 1

    print(f"Generated SDC files: written={written}, skipped_existing={skipped}, unique_targets={len(seen)}")


if __name__ == "__main__":
    main()
